/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.pv168Web.gui;

import cz.pv168Web.model.Land;

/**
 *
 * @author Tomas
 */
public class LandDetail extends javax.swing.JFrame {

    /**
     * Creates new form LandDetail
     */
    public LandDetail() {
        initComponents();
    }
    
    public LandDetail(Land l) {
        initComponents();
        
        
        if (l==null){
            dispose();
        }
        else {
            labelLandIDvalue.setText(l.getLandID()+"");
            labelLandBuildUpAreaValue.setText(l.getBuildUpArea()+"");
            labelLandCatastralAreaValue.setText(l.getCatastralArea());
            labelLandNotesValue.setText(l.getNotes());
            labelLandSizeValue.setText(l.getSize()+"");
            labelLandTypeValue.setText(l.getType());
        }
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelLandDetail = new javax.swing.JLabel();
        labelLandID = new javax.swing.JLabel();
        labelLandSize = new javax.swing.JLabel();
        labelLandCatastralArea = new javax.swing.JLabel();
        labelLandCatastralAreaValue = new javax.swing.JLabel();
        labelLandBuildUpArea = new javax.swing.JLabel();
        labelLandType = new javax.swing.JLabel();
        labelLandNotes = new javax.swing.JLabel();
        labelLandIDvalue = new javax.swing.JLabel();
        labelLandSizeValue = new javax.swing.JLabel();
        labelLandBuildUpAreaValue = new javax.swing.JLabel();
        labelLandTypeValue = new javax.swing.JLabel();
        labelLandNotesValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelLandDetail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelLandDetail.setText("Land Detail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandDetail, gridBagConstraints);

        labelLandID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandID.setText("Land ID :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandID, gridBagConstraints);

        labelLandSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandSize.setText("Size :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandSize, gridBagConstraints);

        labelLandCatastralArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandCatastralArea.setText("Catastral Area :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandCatastralArea, gridBagConstraints);

        labelLandCatastralAreaValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandCatastralAreaValue.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandCatastralAreaValue, gridBagConstraints);

        labelLandBuildUpArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandBuildUpArea.setText("Buildup Area :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandBuildUpArea, gridBagConstraints);

        labelLandType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandType.setText("Type :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandType, gridBagConstraints);

        labelLandNotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandNotes.setText("Notes :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandNotes, gridBagConstraints);

        labelLandIDvalue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandIDvalue.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandIDvalue, gridBagConstraints);

        labelLandSizeValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandSizeValue.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandSizeValue, gridBagConstraints);

        labelLandBuildUpAreaValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandBuildUpAreaValue.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandBuildUpAreaValue, gridBagConstraints);

        labelLandTypeValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandTypeValue.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandTypeValue, gridBagConstraints);

        labelLandNotesValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLandNotesValue.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelLandNotesValue, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelLandBuildUpArea;
    private javax.swing.JLabel labelLandBuildUpAreaValue;
    private javax.swing.JLabel labelLandCatastralArea;
    private javax.swing.JLabel labelLandCatastralAreaValue;
    private javax.swing.JLabel labelLandDetail;
    private javax.swing.JLabel labelLandID;
    private javax.swing.JLabel labelLandIDvalue;
    private javax.swing.JLabel labelLandNotes;
    private javax.swing.JLabel labelLandNotesValue;
    private javax.swing.JLabel labelLandSize;
    private javax.swing.JLabel labelLandSizeValue;
    private javax.swing.JLabel labelLandType;
    private javax.swing.JLabel labelLandTypeValue;
    // End of variables declaration//GEN-END:variables
}
