/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.pv168Web.gui;

import cz.pv168Web.mainPack.MainManager;
import cz.pv168Web.model.Person;
import cz.pv168Web.model.Land;
import cz.pv168Web.model.Ownership;
import cz.pv168Web.utils.DatabaseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tomas
 */
public class MainWindow extends javax.swing.JFrame {

    private final MainManager mainManager;
    private DefaultTableModel personTableModel;
    private DefaultTableModel landTableModel;
    private DefaultTableModel ownershipTableModel;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        mainManager = null;
    }

    public MainWindow(MainManager MM) {
        initComponents();
        mainManager = MM;
        personTableModel = (DefaultTableModel) personTable.getModel();
        landTableModel = (DefaultTableModel) landTable.getModel();
        ownershipTableModel = (DefaultTableModel) ownershipTable1.getModel();
        refreshPersonTable();
        refreshLandTable();
        refreshOwnershipTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        personSortGroup = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        personTab = new javax.swing.JPanel();
        buttonAddPerson = new javax.swing.JButton();
        buttonDetailPerson = new javax.swing.JButton();
        buttonRemovePerson = new javax.swing.JButton();
        buttonUpdatePerson = new javax.swing.JButton();
        labelTablePerson = new javax.swing.JLabel();
        labelTitlePerson = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        landTab = new javax.swing.JPanel();
        labelTitleLand = new javax.swing.JLabel();
        buttonAddLand = new javax.swing.JButton();
        buttonUpdateLand = new javax.swing.JButton();
        buttonRemoveLand = new javax.swing.JButton();
        buttonDetailLand = new javax.swing.JButton();
        labelTableLand = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        landTable = new javax.swing.JTable();
        ownershipTab = new javax.swing.JPanel();
        labelTitleOwnership = new javax.swing.JLabel();
        buttonAddOwnership = new javax.swing.JButton();
        buttonUpdateOwnership = new javax.swing.JButton();
        buttonRemoveOwnership = new javax.swing.JButton();
        buttonDetailOwnership = new javax.swing.JButton();
        labelTableLand1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ownershipTable1 = new javax.swing.JTable();
        customTab = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        personTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        labelCustomTitle = new javax.swing.JLabel();
        labelCustomResults = new javax.swing.JLabel();
        labelCustomNote = new javax.swing.JLabel();
        labelCustomMaxSize = new javax.swing.JLabel();
        labelCustomCatastralArea = new javax.swing.JLabel();
        labelCustomTypeLand = new javax.swing.JLabel();
        labelCustomName = new javax.swing.JLabel();
        labelCustomSurname = new javax.swing.JLabel();
        labelCustomMinSize = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        labelCustomState = new javax.swing.JLabel();
        spinnerMinDuration = new javax.swing.JSpinner();
        spinnerMaxDur = new javax.swing.JSpinner();
        labelCustomMinDuration = new javax.swing.JLabel();
        labelCustomMaxDuration = new javax.swing.JLabel();
        labelCustomPersonTitle = new javax.swing.JLabel();
        labelCustomLandTitle = new javax.swing.JLabel();
        labelCustomOwnershipTitle = new javax.swing.JLabel();
        dateAfter = new org.jdesktop.swingx.JXDatePicker();
        deteBefore = new org.jdesktop.swingx.JXDatePicker();
        labelCustomStartedAdter = new javax.swing.JLabel();
        labelCustomEndedBefore = new javax.swing.JLabel();
        buttonCustomUpdateOpt = new javax.swing.JButton();
        buttonCustomSearch = new javax.swing.JButton();
        buttonCustomDetail = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buttonDBrestart = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAddPerson = new javax.swing.JMenuItem();
        menuAddLand = new javax.swing.JMenuItem();
        menuAddOwnership = new javax.swing.JMenuItem();
        menuResetDB = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(650, 600));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(650, 600));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(650, 600));

        personTab.setMaximumSize(new java.awt.Dimension(650, 600));
        personTab.setMinimumSize(new java.awt.Dimension(650, 600));
        personTab.setPreferredSize(new java.awt.Dimension(650, 600));
        personTab.setLayout(new java.awt.GridBagLayout());

        buttonAddPerson.setText("Add Person");
        buttonAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPersonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        personTab.add(buttonAddPerson, gridBagConstraints);

        buttonDetailPerson.setText("Person Detail");
        buttonDetailPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetailPersonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        personTab.add(buttonDetailPerson, gridBagConstraints);

        buttonRemovePerson.setText("Remove Person");
        buttonRemovePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemovePersonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        personTab.add(buttonRemovePerson, gridBagConstraints);

        buttonUpdatePerson.setText("Upate Person");
        buttonUpdatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdatePersonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        personTab.add(buttonUpdatePerson, gridBagConstraints);

        labelTablePerson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTablePerson.setText("Table of Persons");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        personTab.add(labelTablePerson, gridBagConstraints);

        labelTitlePerson.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitlePerson.setText("Person Management");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        personTab.add(labelTitlePerson, gridBagConstraints);

        personTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname", "Birth Date", "Age", "Birth Number", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(personTable);
        personTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (personTable.getColumnModel().getColumnCount() > 0) {
            personTable.getColumnModel().getColumn(0).setMinWidth(20);
            personTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            personTable.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 429;
        gridBagConstraints.ipady = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        personTab.add(jScrollPane1, gridBagConstraints);

        jTabbedPane1.addTab("Persons", personTab);
        personTab.getAccessibleContext().setAccessibleName("");

        landTab.setMaximumSize(new java.awt.Dimension(650, 600));
        landTab.setMinimumSize(new java.awt.Dimension(650, 600));
        landTab.setPreferredSize(new java.awt.Dimension(650, 600));
        landTab.setLayout(new java.awt.GridBagLayout());

        labelTitleLand.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitleLand.setText("Land Management");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        landTab.add(labelTitleLand, gridBagConstraints);

        buttonAddLand.setText("Add Land");
        buttonAddLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddLandActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        landTab.add(buttonAddLand, gridBagConstraints);

        buttonUpdateLand.setText("Update Land");
        buttonUpdateLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateLandActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        landTab.add(buttonUpdateLand, gridBagConstraints);

        buttonRemoveLand.setText("Remove Land");
        buttonRemoveLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveLandActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        landTab.add(buttonRemoveLand, gridBagConstraints);

        buttonDetailLand.setText("Land");
        buttonDetailLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetailLandActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 311;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        landTab.add(buttonDetailLand, gridBagConstraints);

        labelTableLand.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTableLand.setText("Table of Land");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        landTab.add(labelTableLand, gridBagConstraints);

        landTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Size", "Catastral Area", "BuildUp Area", "Type", "Notes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        landTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(landTable);
        landTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (landTable.getColumnModel().getColumnCount() > 0) {
            landTable.getColumnModel().getColumn(0).setMinWidth(20);
            landTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            landTable.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 667;
        gridBagConstraints.ipady = 545;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        landTab.add(jScrollPane2, gridBagConstraints);

        jTabbedPane1.addTab("Lands", landTab);
        landTab.getAccessibleContext().setAccessibleName("");

        ownershipTab.setMaximumSize(new java.awt.Dimension(650, 600));
        ownershipTab.setMinimumSize(new java.awt.Dimension(650, 600));
        ownershipTab.setPreferredSize(new java.awt.Dimension(650, 600));
        ownershipTab.setLayout(new java.awt.GridBagLayout());

        labelTitleOwnership.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitleOwnership.setText("Land Management");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        ownershipTab.add(labelTitleOwnership, gridBagConstraints);

        buttonAddOwnership.setText("Add Ownership");
        buttonAddOwnership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddOwnershipActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        ownershipTab.add(buttonAddOwnership, gridBagConstraints);

        buttonUpdateOwnership.setText("Update OwnerShip");
        buttonUpdateOwnership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateOwnershipActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        ownershipTab.add(buttonUpdateOwnership, gridBagConstraints);

        buttonRemoveOwnership.setText("RemoveOwnership");
        buttonRemoveOwnership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveOwnershipActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        ownershipTab.add(buttonRemoveOwnership, gridBagConstraints);

        buttonDetailOwnership.setText("Detail Ownership");
        buttonDetailOwnership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetailOwnershipActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 253;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        ownershipTab.add(buttonDetailOwnership, gridBagConstraints);

        labelTableLand1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTableLand1.setText("Table of Ownership");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        ownershipTab.add(labelTableLand1, gridBagConstraints);

        ownershipTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ownershipTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID OwnerShip", "Name", "Surname", "Person ID", "Land ID", "Start Date", "End Date", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ownershipTable1.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(ownershipTable1);
        ownershipTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (ownershipTable1.getColumnModel().getColumnCount() > 0) {
            ownershipTable1.getColumnModel().getColumn(0).setMinWidth(20);
            ownershipTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            ownershipTable1.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 667;
        gridBagConstraints.ipady = 545;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ownershipTab.add(jScrollPane3, gridBagConstraints);

        jTabbedPane1.addTab("Ownerships", ownershipTab);
        ownershipTab.getAccessibleContext().setAccessibleName("");

        customTab.setMaximumSize(new java.awt.Dimension(650, 600));
        customTab.setMinimumSize(new java.awt.Dimension(650, 600));
        customTab.setOpaque(false);
        customTab.setPreferredSize(new java.awt.Dimension(650, 600));
        customTab.setLayout(new java.awt.GridBagLayout());

        personTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        personTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname", "Person ID", "State", "Land ID", "Land type", "Catastral Area", "Size", "Duration", "Date Started", "Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(personTable1);
        personTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (personTable1.getColumnModel().getColumnCount() > 0) {
            personTable1.getColumnModel().getColumn(0).setMinWidth(20);
            personTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            personTable1.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1235;
        gridBagConstraints.ipady = 748;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 4, 0);
        customTab.add(jScrollPane4, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        customTab.add(jComboBox1, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        customTab.add(jComboBox2, gridBagConstraints);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        customTab.add(jComboBox3, gridBagConstraints);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        customTab.add(jComboBox4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        customTab.add(jSpinner1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        customTab.add(jSpinner2, gridBagConstraints);

        jTextField1.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        customTab.add(jTextField1, gridBagConstraints);

        labelCustomTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCustomTitle.setText("Custom Section by specific parameters");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        customTab.add(labelCustomTitle, gridBagConstraints);

        labelCustomResults.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCustomResults.setText("Results");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 0, 0);
        customTab.add(labelCustomResults, gridBagConstraints);

        labelCustomNote.setText("Poznámka");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        customTab.add(labelCustomNote, gridBagConstraints);

        labelCustomMaxSize.setText("Max size of land");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 0, 0);
        customTab.add(labelCustomMaxSize, gridBagConstraints);

        labelCustomCatastralArea.setText("Catastral Area");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        customTab.add(labelCustomCatastralArea, gridBagConstraints);

        labelCustomTypeLand.setText("Type of Land");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        customTab.add(labelCustomTypeLand, gridBagConstraints);

        labelCustomName.setText("Peson name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 0);
        customTab.add(labelCustomName, gridBagConstraints);

        labelCustomSurname.setText("Persons surname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        customTab.add(labelCustomSurname, gridBagConstraints);

        labelCustomMinSize.setText("Min size of land");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 0, 0);
        customTab.add(labelCustomMinSize, gridBagConstraints);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        customTab.add(jComboBox5, gridBagConstraints);

        labelCustomState.setText("State");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        customTab.add(labelCustomState, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        customTab.add(spinnerMinDuration, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        customTab.add(spinnerMaxDur, gridBagConstraints);

        labelCustomMinDuration.setText("Min duration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        customTab.add(labelCustomMinDuration, gridBagConstraints);

        labelCustomMaxDuration.setText("Max duration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        customTab.add(labelCustomMaxDuration, gridBagConstraints);

        labelCustomPersonTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCustomPersonTitle.setText("Person specification");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        customTab.add(labelCustomPersonTitle, gridBagConstraints);

        labelCustomLandTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCustomLandTitle.setText("Land Specification");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        customTab.add(labelCustomLandTitle, gridBagConstraints);

        labelCustomOwnershipTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCustomOwnershipTitle.setText("Ownership specification");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        customTab.add(labelCustomOwnershipTitle, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        customTab.add(dateAfter, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        customTab.add(deteBefore, gridBagConstraints);

        labelCustomStartedAdter.setText("Started after");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        customTab.add(labelCustomStartedAdter, gridBagConstraints);

        labelCustomEndedBefore.setText("Ended befor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        customTab.add(labelCustomEndedBefore, gridBagConstraints);

        buttonCustomUpdateOpt.setText("Update Opitons");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        customTab.add(buttonCustomUpdateOpt, gridBagConstraints);

        buttonCustomSearch.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        customTab.add(buttonCustomSearch, gridBagConstraints);

        buttonCustomDetail.setText("Detail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        customTab.add(buttonCustomDetail, gridBagConstraints);

        jTabbedPane1.addTab("Custom selection", customTab);
        customTab.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        jPanel1.setMaximumSize(new java.awt.Dimension(150, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 600));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        buttonDBrestart.setText("Clear DB");
        buttonDBrestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDBrestartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 10, 0, 10);
        jPanel1.add(buttonDBrestart, gridBagConstraints);

        jButton1.setText("DB Stats");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanel1.add(jButton1, gridBagConstraints);

        getContentPane().add(jPanel1);

        jMenu1.setText("File");

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuAddPerson.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuAddPerson.setText("Add Person");
        menuAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddPersonActionPerformed(evt);
            }
        });
        jMenu2.add(menuAddPerson);

        menuAddLand.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuAddLand.setText("Add Land");
        jMenu2.add(menuAddLand);

        menuAddOwnership.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuAddOwnership.setText("Add Ownership");
        jMenu2.add(menuAddOwnership);

        menuResetDB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuResetDB.setText("Reset Database");
        jMenu2.add(menuResetDB);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        menuHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuHelp.setText("Help");
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });
        jMenu3.add(menuHelp);

        menuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuAbout.setText("About");
        jMenu3.add(menuAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPersonActionPerformed
        PersonInput personInput = new PersonInput(this, true);
        personInput.show();
        if (personInput.getValid()) {
            Runnable r = new Runnable() {
                @Override
                public void run() {
                    synchronized (mainManager) {
                        try {
                            mainManager.createPerson(personInput.getPerson());
                            refreshPersonTable();
                            
                        } catch (DatabaseException ex) {
                            printError(ex.toString());
                        }
                    }
                }
            };

            new Thread(r).start();
        }
    }//GEN-LAST:event_buttonAddPersonActionPerformed

    private void buttonUpdatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdatePersonActionPerformed
        Person p;
        int rownNumber = personTable.getSelectedRow();
        if (rownNumber >= 0) {
            Long personId = Long.parseLong(personTableModel.getValueAt(rownNumber, 0).toString());
            try {
                p = mainManager.getPersonById(personId);
                PersonInput personInput = new PersonInput(this, true, p);
                personInput.show();
                if (personInput.getValid()) {

                    Runnable r = new Runnable() {
                        @Override
                        public void run() {
                            synchronized (mainManager) {
                                try {
                                    mainManager.updatePerson(personInput.getPerson());
                                    refreshPersonTable();
                                } catch (DatabaseException ex) {
                                    printError(ex.toString());
                                }
                            }
                        }
                    };
                    new Thread(r).start();
                }
            } catch (DatabaseException ex) {
                printError(ex.toString());
            }

        }
       
    }//GEN-LAST:event_buttonUpdatePersonActionPerformed

    private void buttonRemovePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemovePersonActionPerformed
        int rownNumber = personTable.getSelectedRow();

        if (rownNumber >= 0) {
            Long personId = Long.parseLong(personTableModel.getValueAt(rownNumber, 0).toString());

            Runnable r = new Runnable() {
                @Override
                public void run() {
                    synchronized (mainManager) {
                        try {
                            mainManager.removePerson(personId);
                        } catch (DatabaseException ex) {
                            printError(ex.toString());
                        }
                        refreshPersonTable();
                    }
                }
            };
             new Thread(r).start();
        }
    }//GEN-LAST:event_buttonRemovePersonActionPerformed

    private void buttonDetailPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetailPersonActionPerformed
        int rownNumber = personTable.getSelectedRow();

        if (rownNumber >= 0) {
            Long personId = Long.parseLong(personTableModel.getValueAt(rownNumber, 0).toString());

            Runnable r = new Runnable() {
                @Override
                public void run() {
                    synchronized (mainManager) {
                        try {
                            PersonDetail pd = new PersonDetail(mainManager.getPersonById(personId));
                            pd.show();
                        } catch (DatabaseException ex) {
                            printError(ex.toString());
                        }
                        refreshPersonTable();
                    }
                }
            };
             new Thread(r).start();
        }
    }//GEN-LAST:event_buttonDetailPersonActionPerformed

    private void buttonDBrestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDBrestartActionPerformed

        Runnable r = new Runnable() {
            @Override
            public void run() {
                synchronized (mainManager) {
                    try {
                        mainManager.deleteDB();
                        mainManager.createDB();
                    } catch (DatabaseException ex) {

                    }
                    refreshPersonTable();
                }
            }
        };

        new Thread(r).start();
    }//GEN-LAST:event_buttonDBrestartActionPerformed

    private void buttonAddLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddLandActionPerformed
        LandInput landInput = new LandInput(this, true);
        landInput.show();
        if (landInput.getValid()) {
            Runnable r = new Runnable() {
                @Override
                public void run() {
                    synchronized (mainManager) {
                        try {
                            mainManager.createLand(landInput.getLand());
                            refreshLandTable();
                        } catch (DatabaseException ex) {
                            printError(ex.toString());
                        }
                    }
                }
            };

            new Thread(r).start();
        }
    }//GEN-LAST:event_buttonAddLandActionPerformed

    private void buttonUpdateLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateLandActionPerformed
       Land l;
        int rownNumber = landTable.getSelectedRow();
        if (rownNumber >= 0) {
            Long landId = Long.parseLong(landTableModel.getValueAt(rownNumber, 0).toString());
            try {
                l = mainManager.getLandById(landId);
                LandInput landInput = new LandInput(this, true, l);
                landInput.show();
                if (landInput.getValid()) {

                    Runnable r = new Runnable() {
                        @Override
                        public void run() {
                            synchronized (mainManager) {
                                try {
                                    mainManager.updateLand(landInput.getLand());
                                    refreshLandTable();
                                } catch (DatabaseException ex) {
                                    printError(ex.toString());
                                }
                            }
                        }
                    };
                    new Thread(r).start();
                }
            } catch (DatabaseException ex) {
                printError(ex.toString());
            }

        }
    }//GEN-LAST:event_buttonUpdateLandActionPerformed

    private void buttonRemoveLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveLandActionPerformed
         int rownNumber = landTable.getSelectedRow();

        if (rownNumber >= 0) {
            Long landId = Long.parseLong(landTableModel.getValueAt(rownNumber, 0).toString());

            Runnable r = new Runnable() {
                @Override
                public void run() {
                    synchronized (mainManager) {
                        try {
                            mainManager.removeLand(landId);
                        } catch (DatabaseException ex) {
                            printError(ex.toString());
                        }
                        refreshLandTable();
                    }
                }
            };
             new Thread(r).start();
        }
    }//GEN-LAST:event_buttonRemoveLandActionPerformed

    private void buttonDetailLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetailLandActionPerformed
                 int rownNumber = landTable.getSelectedRow();

        if (rownNumber >= 0) {
            Long landId = Long.parseLong(landTableModel.getValueAt(rownNumber, 0).toString());

            Runnable r = new Runnable() {
                @Override
                public void run() {
                    synchronized (mainManager) {
                        try {
                            LandDetail ld = new LandDetail(mainManager.getLandById(landId));
                            ld.show();
                        } catch (DatabaseException ex) {
                            printError(ex.toString());
                        }
                        refreshLandTable();
                    }
                }
            };
             new Thread(r).start();
        }
    }//GEN-LAST:event_buttonDetailLandActionPerformed

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelpActionPerformed

    private void buttonDetailOwnershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetailOwnershipActionPerformed
        
    }//GEN-LAST:event_buttonDetailOwnershipActionPerformed

    private void buttonRemoveOwnershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveOwnershipActionPerformed
        int rownNumber = ownershipTable1.getSelectedRow();

        if (rownNumber >= 0) {
            Long ownershipId = Long.parseLong(ownershipTableModel.getValueAt(rownNumber, 0).toString());

            Runnable r = new Runnable() {
                @Override
                public void run() {
                    synchronized (mainManager) {
                        try {
                            mainManager.removeOwnership(ownershipId);
                            refreshOwnershipTable();
                        } catch (DatabaseException ex) {
                            printError(ex.toString());
                        }
                        refreshLandTable();
                    }
                }
            };
             new Thread(r).start();
        }
    }//GEN-LAST:event_buttonRemoveOwnershipActionPerformed

    private void buttonUpdateOwnershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateOwnershipActionPerformed
        Ownership o;
        int rownNumber = ownershipTable1.getSelectedRow();
        if (rownNumber >= 0) {
            Long ownershipId = Long.parseLong(ownershipTableModel.getValueAt(rownNumber, 0).toString());
            try {
                o = mainManager.getOwnershipById(ownershipId);
                OwnershipInput ownershipInput = new OwnershipInput(this, true,mainManager.getPersonIDArray(), mainManager.getLandIDArray(), o);
                ownershipInput.show();
                if (ownershipInput.getValid()) {

                    Runnable r = new Runnable() {
                        @Override
                        public void run() {
                            synchronized (mainManager) {
                                try {
                                    mainManager.updateOwnership(ownershipInput.getOwnership());
                                    refreshOwnershipTable();
                                } catch (DatabaseException ex) {
                                    printError(ex.toString());
                                }
                            }
                        }
                    };
                    new Thread(r).start();
                }
            } catch (DatabaseException ex) {
                printError(ex.toString());
            }

        }
    }//GEN-LAST:event_buttonUpdateOwnershipActionPerformed

    private void buttonAddOwnershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddOwnershipActionPerformed
        try {
            OwnershipInput ownershipInput = new OwnershipInput(this, true, mainManager.getPersonIDArray() , mainManager.getLandIDArray());
        
            ownershipInput.show();
            if (ownershipInput.getValid()) {
                Runnable r = new Runnable() {
                    @Override
                    public void run() {
                        synchronized (mainManager) {
                            try {
                                mainManager.createOwnership(ownershipInput.getOwnership());
                                refreshOwnershipTable();
                            } catch (DatabaseException ex) {
                                printError(ex.toString());
                            }
                        }
                    }
                };

                new Thread(r).start();
            }
        }catch(DatabaseException ex){
           printError(ex.toString()); 
        }
    }//GEN-LAST:event_buttonAddOwnershipActionPerformed

    private void menuAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAddPersonActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddLand;
    private javax.swing.JButton buttonAddOwnership;
    private javax.swing.JButton buttonAddPerson;
    private javax.swing.JButton buttonCustomDetail;
    private javax.swing.JButton buttonCustomSearch;
    private javax.swing.JButton buttonCustomUpdateOpt;
    private javax.swing.JButton buttonDBrestart;
    private javax.swing.JButton buttonDetailLand;
    private javax.swing.JButton buttonDetailOwnership;
    private javax.swing.JButton buttonDetailPerson;
    private javax.swing.JButton buttonRemoveLand;
    private javax.swing.JButton buttonRemoveOwnership;
    private javax.swing.JButton buttonRemovePerson;
    private javax.swing.JButton buttonUpdateLand;
    private javax.swing.JButton buttonUpdateOwnership;
    private javax.swing.JButton buttonUpdatePerson;
    private javax.swing.JPanel customTab;
    private org.jdesktop.swingx.JXDatePicker dateAfter;
    private org.jdesktop.swingx.JXDatePicker deteBefore;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCustomCatastralArea;
    private javax.swing.JLabel labelCustomEndedBefore;
    private javax.swing.JLabel labelCustomLandTitle;
    private javax.swing.JLabel labelCustomMaxDuration;
    private javax.swing.JLabel labelCustomMaxSize;
    private javax.swing.JLabel labelCustomMinDuration;
    private javax.swing.JLabel labelCustomMinSize;
    private javax.swing.JLabel labelCustomName;
    private javax.swing.JLabel labelCustomNote;
    private javax.swing.JLabel labelCustomOwnershipTitle;
    private javax.swing.JLabel labelCustomPersonTitle;
    private javax.swing.JLabel labelCustomResults;
    private javax.swing.JLabel labelCustomStartedAdter;
    private javax.swing.JLabel labelCustomState;
    private javax.swing.JLabel labelCustomSurname;
    private javax.swing.JLabel labelCustomTitle;
    private javax.swing.JLabel labelCustomTypeLand;
    private javax.swing.JLabel labelTableLand;
    private javax.swing.JLabel labelTableLand1;
    private javax.swing.JLabel labelTablePerson;
    private javax.swing.JLabel labelTitleLand;
    private javax.swing.JLabel labelTitleOwnership;
    private javax.swing.JLabel labelTitlePerson;
    private javax.swing.JPanel landTab;
    private javax.swing.JTable landTable;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuAddLand;
    private javax.swing.JMenuItem menuAddOwnership;
    private javax.swing.JMenuItem menuAddPerson;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuHelp;
    private javax.swing.JMenuItem menuResetDB;
    private javax.swing.JPanel ownershipTab;
    private javax.swing.JTable ownershipTable1;
    private javax.swing.ButtonGroup personSortGroup;
    private javax.swing.JPanel personTab;
    private javax.swing.JTable personTable;
    private javax.swing.JTable personTable1;
    private javax.swing.JSpinner spinnerMaxDur;
    private javax.swing.JSpinner spinnerMinDuration;
    // End of variables declaration//GEN-END:variables

    private void refreshPersonTable() {
        try {
            // clear table 
            while (personTableModel.getRowCount() > 0) {
                personTableModel.removeRow(personTableModel.getRowCount() - 1);
            }

            List<Person> list = mainManager.getPersonList();
            for (Person p : list) {
                personTableModel.addRow(p.toArray());
            }

        } catch (DatabaseException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void refreshLandTable() {
        try {
            // clear table 
            while (landTableModel.getRowCount() > 0) {
                landTableModel.removeRow(landTableModel.getRowCount() - 1);
            }

            List<Land> list = mainManager.getLandList();
            for (Land l : list) {
                landTableModel.addRow(l.toArray());
            }

        } catch (DatabaseException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void refreshOwnershipTable() {
        try {
            // clear table 
            while (ownershipTableModel.getRowCount() > 0) {
                ownershipTableModel.removeRow(ownershipTableModel.getRowCount() - 1);
            }

            List<Ownership> list = mainManager.getOwnershipList();
            for (Ownership o : list) {
                
                ownershipTableModel.addRow(mainManager.getOwnershipArray(o));
                
            }

        } catch (DatabaseException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void printError(String msg) {
        JOptionPane.showMessageDialog(null, msg, "Error with Database", JOptionPane.ERROR_MESSAGE);
    }

}
