/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.pv168Web.gui;

import cz.pv168Web.model.Person;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Tomas
 */
public class PersonDetail extends javax.swing.JFrame {

    /**
     * Creates new form PersonDetail
     */
    public PersonDetail() {
        initComponents();
    }
    
    public PersonDetail(Person p) {
        initComponents();
        
        if (p==null) dispose();
        else {
            labelPersonIDvalue.setText(p.getPersonId()+"");
            labelPersonNameValue.setText(p.getName());
            labelPersonSurnameValue.setText(p.getSurname());
            labelPersonBirthNumberValue.setText(p.getBirthNumber());
            labelPersonStateValue.setText(p.getState());
            
            DateFormat format = new SimpleDateFormat("dd.MM.yyyy");
            Date birthDate = p.getBirthDate();
            labelPersonBirthdateValue.setText(format.format(p.getBirthDate()));
           
            LocalDate birth = LocalDate.parse(new SimpleDateFormat("yyyy-MM-dd").format(birthDate));
            LocalDate today = LocalDate.now();
            
            Period period = Period.between(birth, today);    
            labelPersonAgeValue.setText(period.getYears()+"");
        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelPersonState = new javax.swing.JLabel();
        labelPersonBirthNumber = new javax.swing.JLabel();
        labelPersonId = new javax.swing.JLabel();
        labelPersonDetailTitle = new javax.swing.JLabel();
        labelPersonName = new javax.swing.JLabel();
        labelPersonSurname = new javax.swing.JLabel();
        labelPersonBirthdate = new javax.swing.JLabel();
        labelPersonAge = new javax.swing.JLabel();
        labelPersonIDvalue = new javax.swing.JLabel();
        labelPersonNameValue = new javax.swing.JLabel();
        labelPersonSurnameValue = new javax.swing.JLabel();
        labelPersonBirthdateValue = new javax.swing.JLabel();
        labelPersonBirthNumberValue = new javax.swing.JLabel();
        labelPersonStateValue = new javax.swing.JLabel();
        labelPersonAgeValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelPersonState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/pv168Web/gui/PersonDetail"); // NOI18N
        labelPersonState.setText(bundle.getString("PersonDetail.labelPersonState.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonState, gridBagConstraints);

        labelPersonBirthNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonBirthNumber.setText(bundle.getString("PersonDetail.labelPersonBirthNumber.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonBirthNumber, gridBagConstraints);

        labelPersonId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonId.setText(bundle.getString("PersonDetail.labelPersonId.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonId, gridBagConstraints);

        labelPersonDetailTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelPersonDetailTitle.setText(bundle.getString("PersonDetail.labelPersonDetailTitle.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(labelPersonDetailTitle, gridBagConstraints);

        labelPersonName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonName.setText(bundle.getString("PersonDetail.labelPersonName.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonName, gridBagConstraints);

        labelPersonSurname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonSurname.setText(bundle.getString("PersonDetail.labelPersonSurname.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonSurname, gridBagConstraints);

        labelPersonBirthdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonBirthdate.setText(bundle.getString("PersonDetail.labelPersonBirthdate.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonBirthdate, gridBagConstraints);

        labelPersonAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonAge.setText(bundle.getString("PersonDetail.labelPersonAge.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonAge, gridBagConstraints);

        labelPersonIDvalue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonIDvalue.setText(bundle.getString("PersonDetail.text")); // NOI18N
        labelPersonIDvalue.setMaximumSize(new java.awt.Dimension(200, 17));
        labelPersonIDvalue.setMinimumSize(new java.awt.Dimension(200, 17));
        labelPersonIDvalue.setName(""); // NOI18N
        labelPersonIDvalue.setPreferredSize(new java.awt.Dimension(200, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonIDvalue, gridBagConstraints);

        labelPersonNameValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonNameValue.setText(bundle.getString("PersonDetail.labelPersonNameValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonNameValue, gridBagConstraints);

        labelPersonSurnameValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonSurnameValue.setText(bundle.getString("PersonDetail.labelPersonSurnameValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonSurnameValue, gridBagConstraints);

        labelPersonBirthdateValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonBirthdateValue.setText(bundle.getString("PersonDetail.labelPersonBirthdateValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonBirthdateValue, gridBagConstraints);

        labelPersonBirthNumberValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonBirthNumberValue.setText(bundle.getString("PersonDetail.labelPersonBirthNumberValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonBirthNumberValue, gridBagConstraints);

        labelPersonStateValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonStateValue.setText(bundle.getString("PersonDetail.labelPersonStateValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonStateValue, gridBagConstraints);

        labelPersonAgeValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPersonAgeValue.setText(bundle.getString("PersonDetail.labelPersonAgeValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelPersonAgeValue, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelPersonAge;
    private javax.swing.JLabel labelPersonAgeValue;
    private javax.swing.JLabel labelPersonBirthNumber;
    private javax.swing.JLabel labelPersonBirthNumberValue;
    private javax.swing.JLabel labelPersonBirthdate;
    private javax.swing.JLabel labelPersonBirthdateValue;
    private javax.swing.JLabel labelPersonDetailTitle;
    private javax.swing.JLabel labelPersonIDvalue;
    private javax.swing.JLabel labelPersonId;
    private javax.swing.JLabel labelPersonName;
    private javax.swing.JLabel labelPersonNameValue;
    private javax.swing.JLabel labelPersonState;
    private javax.swing.JLabel labelPersonStateValue;
    private javax.swing.JLabel labelPersonSurname;
    private javax.swing.JLabel labelPersonSurnameValue;
    // End of variables declaration//GEN-END:variables
}
